### ISSUE TITLE
No module named 'indy_client'

### ISSUE THREAD

**Issue by larsmunaf** [brycecurtis/indy-tutorial-sandbox#7]
When executing `make local run-demo`, python throws an error:
```
Traceback (most recent call last):
  File "./indy-cli", line 51, in <module>
    from indy_client.cli.cli import IndyCli
ImportError: No module named 'indy_client'
`````

It appears after fixing a previous error by setting the respective variables manually:
```
Traceback (most recent call last):
  File "./indy-cli", line 42, in <module>
    baseDir = os.path.expanduser(config.CLI_BASE_DIR)
AttributeError: module 'indy_config.py' has no attribute 'CLI_BASE_DIR'
```

Are those error messages somehow correlated? Some files and values seem to be missing/are not been generated by the Dockerfile. Is it because of version mismatches?

**Comment by doyajii1** [comment]
@larsmunaf have you find solution to your problem?

**Comment by larsmunaf** [comment]
I still didn't. Probably, I misunderstood the whole setup, but that's why I opened this issue.

**Comment by doyajii1** [comment]
@larsmunaf I was getting same error and was also wondering about same issue.

**Comment by leehanrick** [comment]
How was this issue solved? I am also facing the same issue

**Comment by nachikettapas** [comment]
Anyone able to find a solution to this problem?
